version: '3.1'
services:
#  frontend:
#    container_name: 'frontend'
#    build: './../frontend'
#    ports:
#      - "8080:80"
#    depends_on:
#      - backend
#    networks:
#      frontend:
#        aliases:
#          - frontend
#    deploy:
#      resources:
#        limits:
#          memory: 256M
#  backend:
#    container_name: 'backend'
#    build: './../backend'
#    ports:
#      - "8081:8081"
#    depends_on:
#      - db
#    networks:
#      frontend:
#        aliases:
#          - backend
#      backend:
#        aliases:
#          - backend
#    deploy:
#      resources:
#        limits:
#          memory: 1G
#    environment:
#      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/postgres
  db:
    container_name: 'db'
    image: postgres
    ports:
      - "5432:5432"
    restart: unless-stopped
    networks:
      - backend
    deploy:
      resources:
        limits:
          memory: 128M
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: P@ssw0rd
      PGDATA: /var/lib/postgresql/data
      POSTGRES_DB: ksiazka_kucharska
    volumes:
      - postgres:/data/postgres
  mail-dev:
    container_name: 'mail-dev-server'
    image: maildev/maildev
    ports:
      - "1080:1080"
      - "1025:1025"

volumes:
  postgres:
    driver: local

networks:
  backend:
    driver: bridge
  frontend:
    driver: bridge