spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ksiazka_kucharska
    username: admin
    password: P@ssw0rd
    driver-class-name: org.postgresql.Driver
  sql:
    init:
      mode: always
  jpa:
    hibernate:
      ddl-auto: create
    defer-datasource-initialization: true
    database: postgresql
  mail:
    host: localhost
    port: 1025
    username: admin
    password: P@ssw0rd
    properties:
      mail:
        smtp:
          trust: "*"
        auth: true
        starttls:
          enable: true
        connectiontimeout: 5000
        timeout: 3000
        writetimeout: 5000
application:
  security:
    jwt:
      secret-key: 7ae81f1f2e3b87755c6716f8ff93c7da45374bcdbabe45e7ad81c81e85
      expiration: 86400000
  mailing:
    frontend:
      activation-url: http://localhost:8080/activate-account
