spring:
  profiles:
    active: dev
  servlet:
    multipart:
      max-file-size: 25MB
springdoc:
  default-produces-media-type: application/json

server:
  port: 8081
  servlet:
    context-path: /api/v1/