INSERT INTO ingredients (id, name) VALUES (1, 'Mąka');
INSERT INTO ingredients (id, name) VALUES (2, 'Sól');
INSERT INTO ingredients (id, name) VALUES (3, 'Jajka');
INSERT INTO ingredients (id, name) VALUES (4, 'Kiełbasa');
INSERT INTO ingredients (id, name) VALUES (5, 'Cukier');
INSERT INTO ingredients (id, name) VALUES (6, 'Pieprz');
INSERT INTO ingredients (id, name) VALUES (7, 'Pierś z kurczaka');
INSERT INTO ingredients (id, name) VALUES (8, 'Drożdże');
INSERT INTO ingredients (id, name) VALUES (9, 'Cukier wanilinowy');
INSERT INTO ingredients (id, name) VALUES (10, 'Jabłko');
INSERT INTO ingredients (id, name) VALUES (11, 'Śliwka');